
all: daq func scpi sour timer1

daq:
	./test_dev_ad974_mcp4922.py

func:
	./test_func_dec.py
	./test_func_div.py
	./test_func_int.py
	./test_func_mul.py

scpi:
	./test_scpi_CC.py

sour:
	./test_sour_temp.py

timer1:
	./test_timer1.py
