
all: input math

input:
	./test_input_version.py ${DEV_PORT} ${BAUDRATE}
	./test_input_num.py ${DEV_PORT} ${BAUDRATE}

math:
	./test_math_div.py ${DEV_PORT} ${BAUDRATE}
	./test_math_mul.py ${DEV_PORT} ${BAUDRATE}

