
all: daq input math

daq:
	./test_dev_ad974_mcp4922.py ${DEV_PORT} ${BAUDRATE}

input:
	./test_input_version.py ${DEV_PORT} ${BAUDRATE}
	./test_input_num.py

math:
	./test_math_div.py ${DEV_PORT} ${BAUDRATE}
	./test_math_mul.py ${DEV_PORT} ${BAUDRATE}

