
all: daq input math scpi sour timer1

daq:
	./test_dev_ad974_mcp4922.py

input:
	./test_input.py

math:
	./test_math_div.py
	./test_math_mul.py

scpi:
	./test_scpi_CC.py

sour:
	./test_sour_temp.py

timer1:
	./test_timer1.py
