#ifndef __SCPI_ERR_H__
#define __SCPI_ERR_H__

typedef struct {
	const char *str_P;
	uint8_t SES_P;
} SCPI_err_t;

extern const SCPI_err_t SCPI_err_2;
extern const SCPI_err_t SCPI_err_1;
extern const SCPI_err_t SCPI_err_0;
extern const SCPI_err_t SCPI_err_100;
extern const SCPI_err_t SCPI_err_101;
extern const SCPI_err_t SCPI_err_102;
extern const SCPI_err_t SCPI_err_103;
extern const SCPI_err_t SCPI_err_104;
extern const SCPI_err_t SCPI_err_105;
extern const SCPI_err_t SCPI_err_108;
extern const SCPI_err_t SCPI_err_109;
extern const SCPI_err_t SCPI_err_110;
extern const SCPI_err_t SCPI_err_111;
extern const SCPI_err_t SCPI_err_112;
extern const SCPI_err_t SCPI_err_113;
extern const SCPI_err_t SCPI_err_114;
extern const SCPI_err_t SCPI_err_115;
extern const SCPI_err_t SCPI_err_120;
extern const SCPI_err_t SCPI_err_121;
extern const SCPI_err_t SCPI_err_123;
extern const SCPI_err_t SCPI_err_124;
extern const SCPI_err_t SCPI_err_128;
extern const SCPI_err_t SCPI_err_130;
extern const SCPI_err_t SCPI_err_131;
extern const SCPI_err_t SCPI_err_134;
extern const SCPI_err_t SCPI_err_138;
extern const SCPI_err_t SCPI_err_140;
extern const SCPI_err_t SCPI_err_141;
extern const SCPI_err_t SCPI_err_144;
extern const SCPI_err_t SCPI_err_148;
extern const SCPI_err_t SCPI_err_150;
extern const SCPI_err_t SCPI_err_151;
extern const SCPI_err_t SCPI_err_158;
extern const SCPI_err_t SCPI_err_160;
extern const SCPI_err_t SCPI_err_161;
extern const SCPI_err_t SCPI_err_168;
extern const SCPI_err_t SCPI_err_170;
extern const SCPI_err_t SCPI_err_171;
extern const SCPI_err_t SCPI_err_178;
extern const SCPI_err_t SCPI_err_180;
extern const SCPI_err_t SCPI_err_181;
extern const SCPI_err_t SCPI_err_183;
extern const SCPI_err_t SCPI_err_184;
extern const SCPI_err_t SCPI_err_200;
extern const SCPI_err_t SCPI_err_201;
extern const SCPI_err_t SCPI_err_202;
extern const SCPI_err_t SCPI_err_203;
extern const SCPI_err_t SCPI_err_210;
extern const SCPI_err_t SCPI_err_211;
extern const SCPI_err_t SCPI_err_212;
extern const SCPI_err_t SCPI_err_213;
extern const SCPI_err_t SCPI_err_214;
extern const SCPI_err_t SCPI_err_215;
extern const SCPI_err_t SCPI_err_220;
extern const SCPI_err_t SCPI_err_221;
extern const SCPI_err_t SCPI_err_222;
extern const SCPI_err_t SCPI_err_223;
extern const SCPI_err_t SCPI_err_224;
extern const SCPI_err_t SCPI_err_225;
extern const SCPI_err_t SCPI_err_226;
extern const SCPI_err_t SCPI_err_230;
extern const SCPI_err_t SCPI_err_231;
extern const SCPI_err_t SCPI_err_232;
extern const SCPI_err_t SCPI_err_233;
extern const SCPI_err_t SCPI_err_240;
extern const SCPI_err_t SCPI_err_241;
extern const SCPI_err_t SCPI_err_250;
extern const SCPI_err_t SCPI_err_251;
extern const SCPI_err_t SCPI_err_252;
extern const SCPI_err_t SCPI_err_253;
extern const SCPI_err_t SCPI_err_254;
extern const SCPI_err_t SCPI_err_255;
extern const SCPI_err_t SCPI_err_256;
extern const SCPI_err_t SCPI_err_257;
extern const SCPI_err_t SCPI_err_258;
extern const SCPI_err_t SCPI_err_260;
extern const SCPI_err_t SCPI_err_261;
extern const SCPI_err_t SCPI_err_270;
extern const SCPI_err_t SCPI_err_271;
extern const SCPI_err_t SCPI_err_272;
extern const SCPI_err_t SCPI_err_273;
extern const SCPI_err_t SCPI_err_274;
extern const SCPI_err_t SCPI_err_275;
extern const SCPI_err_t SCPI_err_276;
extern const SCPI_err_t SCPI_err_277;
extern const SCPI_err_t SCPI_err_278;
extern const SCPI_err_t SCPI_err_280;
extern const SCPI_err_t SCPI_err_281;
extern const SCPI_err_t SCPI_err_282;
extern const SCPI_err_t SCPI_err_283;
extern const SCPI_err_t SCPI_err_284;
extern const SCPI_err_t SCPI_err_285;
extern const SCPI_err_t SCPI_err_286;
extern const SCPI_err_t SCPI_err_290;
extern const SCPI_err_t SCPI_err_291;
extern const SCPI_err_t SCPI_err_292;
extern const SCPI_err_t SCPI_err_293;
extern const SCPI_err_t SCPI_err_300;
extern const SCPI_err_t SCPI_err_310;
extern const SCPI_err_t SCPI_err_311;
extern const SCPI_err_t SCPI_err_312;
extern const SCPI_err_t SCPI_err_313;
extern const SCPI_err_t SCPI_err_314;
extern const SCPI_err_t SCPI_err_315;
extern const SCPI_err_t SCPI_err_320;
extern const SCPI_err_t SCPI_err_321;
extern const SCPI_err_t SCPI_err_330;
extern const SCPI_err_t SCPI_err_340;
extern const SCPI_err_t SCPI_err_350;
extern const SCPI_err_t SCPI_err_360;
extern const SCPI_err_t SCPI_err_361;
extern const SCPI_err_t SCPI_err_362;
extern const SCPI_err_t SCPI_err_363;
extern const SCPI_err_t SCPI_err_365;
extern const SCPI_err_t SCPI_err_400;
extern const SCPI_err_t SCPI_err_410;
extern const SCPI_err_t SCPI_err_420;
extern const SCPI_err_t SCPI_err_430;
extern const SCPI_err_t SCPI_err_440;
extern const SCPI_err_t SCPI_err_500;
extern const SCPI_err_t SCPI_err_600;
extern const SCPI_err_t SCPI_err_700;
extern const SCPI_err_t SCPI_err_800;

const SCPI_err_t* SCPI_err_pop(void);
void SCPI_err_queue_reset(void);
void SCPI_err_set(const SCPI_err_t *e);

#endif
